#!/bin/sh -e

# loop over proto files
for proto_file in protos/*.proto
do
    # generate python code from proto files
    python -m grpc_tools.protoc \
        -I./protos \
        --python_out=./protos \
        --pyi_out=./protos \
        --grpc_python_out=./protos \
        "$proto_file"
done
